// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hncnhxmusspfrqnksnwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhuY25oeG11c3NwZnJxbmtzbndmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0MDY4MDAsImV4cCI6MjA1Mzk4MjgwMH0.2VALng6SNucPoD88v4pq4BaZNLg54xBHk4QA1IW7ngo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);